name: Deploy Next.js app to Vercel

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test:check        
        env:
          RESEND_TOKEN: ${{ secrets.RESEND_TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      
      - name: Run type check
        run: yarn typecheck
      
      - name: Run database migrations
        run: yarn migrate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Generate Prisma client
        run: yarn generate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }} 
          
      - name: Seed content
        run: yarn sync
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          STRIPE_SECRET: ${{ secrets.STRIPE_SECRET }}
    
      - name: Index MeiliSearch
        run: yarn index
        env:
          MEILISEARCH_HOST: ${{ secrets.MEILISEARCH_HOST }}
          MEILISEARCH_MASTER_KEY: ${{ secrets.MEILISEARCH_MASTER_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
          vercel-args: '--prod'